model: RCAN         # Options: SRCNN, SvOcSRCNN, VDSR_SA, VDSR, RCAN
epochs: 1
scale: 4            # Upscaling factor (e.g., 2, 4)
loss: combined           # Options: mse, charbonnier, combined
save_dir: outputs/rcan
use_wandb: false
batch_size: 8